name: Build Web App

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    
    runs-on: windows-latest
    
    env:
      SOLUTION_FILE_PATH: 'NetFrameworkDeployIIS.sln'
      SOLUTION_NAME: 'NetFrameworkDeployIIS'
    
    steps:
      - uses: actions/checkout@v1
        name: Checkout Code

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        with:
          nuget-version: '5.x'

      - name: Restore NuGet Packages
        run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

      - name: Build and Publish Web App
        run: msbuild ${{ env.SOLUTION_FILE_PATH }} /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: published_webapp
          path: ${{ env.SOLUTION_NAME }}\bin\Release\Publish